# Cấu hình Listener cho TLS
listener 8883
protocol mqtt

# Quản lý truy cập
allow_anonymous false
# password_file ./passwd
# Đường dẫn đến chứng chỉ (Sử dụng đường dẫn tương đối hoặc tuyệt đối)
cafile ./ca.crt
certfile ./server.crt
keyfile ./server.key

# Yêu cầu Client cũng phải trình diện chứng chỉ để xác thực 2 chiều (Mutual TLS)
require_certificate true
use_identity_as_username true